// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flux

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetFluxInstall(ctx *pulumi.Context, args *GetFluxInstallArgs, opts ...pulumi.InvokeOption) (*GetFluxInstallResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetFluxInstallResult
	err := ctx.Invoke("flux:index/getFluxInstall:getFluxInstall", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFluxInstall.
type GetFluxInstallArgs struct {
	Baseurl            *string  `pulumi:"baseurl"`
	ClusterDomain      *string  `pulumi:"clusterDomain"`
	Components         []string `pulumi:"components"`
	ComponentsExtras   []string `pulumi:"componentsExtras"`
	ImagePullSecrets   *string  `pulumi:"imagePullSecrets"`
	LogLevel           *string  `pulumi:"logLevel"`
	Namespace          *string  `pulumi:"namespace"`
	NetworkPolicy      *bool    `pulumi:"networkPolicy"`
	Registry           *string  `pulumi:"registry"`
	TargetPath         string   `pulumi:"targetPath"`
	TolerationKeys     []string `pulumi:"tolerationKeys"`
	Version            *string  `pulumi:"version"`
	WatchAllNamespaces *bool    `pulumi:"watchAllNamespaces"`
}

// A collection of values returned by getFluxInstall.
type GetFluxInstallResult struct {
	Baseurl            *string  `pulumi:"baseurl"`
	ClusterDomain      *string  `pulumi:"clusterDomain"`
	Components         []string `pulumi:"components"`
	ComponentsExtras   []string `pulumi:"componentsExtras"`
	Content            string   `pulumi:"content"`
	Id                 string   `pulumi:"id"`
	ImagePullSecrets   *string  `pulumi:"imagePullSecrets"`
	LogLevel           *string  `pulumi:"logLevel"`
	Namespace          *string  `pulumi:"namespace"`
	NetworkPolicy      *bool    `pulumi:"networkPolicy"`
	Path               string   `pulumi:"path"`
	Registry           *string  `pulumi:"registry"`
	TargetPath         string   `pulumi:"targetPath"`
	TolerationKeys     []string `pulumi:"tolerationKeys"`
	Version            *string  `pulumi:"version"`
	WatchAllNamespaces *bool    `pulumi:"watchAllNamespaces"`
}

func GetFluxInstallOutput(ctx *pulumi.Context, args GetFluxInstallOutputArgs, opts ...pulumi.InvokeOption) GetFluxInstallResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetFluxInstallResult, error) {
			args := v.(GetFluxInstallArgs)
			r, err := GetFluxInstall(ctx, &args, opts...)
			var s GetFluxInstallResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetFluxInstallResultOutput)
}

// A collection of arguments for invoking getFluxInstall.
type GetFluxInstallOutputArgs struct {
	Baseurl            pulumi.StringPtrInput   `pulumi:"baseurl"`
	ClusterDomain      pulumi.StringPtrInput   `pulumi:"clusterDomain"`
	Components         pulumi.StringArrayInput `pulumi:"components"`
	ComponentsExtras   pulumi.StringArrayInput `pulumi:"componentsExtras"`
	ImagePullSecrets   pulumi.StringPtrInput   `pulumi:"imagePullSecrets"`
	LogLevel           pulumi.StringPtrInput   `pulumi:"logLevel"`
	Namespace          pulumi.StringPtrInput   `pulumi:"namespace"`
	NetworkPolicy      pulumi.BoolPtrInput     `pulumi:"networkPolicy"`
	Registry           pulumi.StringPtrInput   `pulumi:"registry"`
	TargetPath         pulumi.StringInput      `pulumi:"targetPath"`
	TolerationKeys     pulumi.StringArrayInput `pulumi:"tolerationKeys"`
	Version            pulumi.StringPtrInput   `pulumi:"version"`
	WatchAllNamespaces pulumi.BoolPtrInput     `pulumi:"watchAllNamespaces"`
}

func (GetFluxInstallOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFluxInstallArgs)(nil)).Elem()
}

// A collection of values returned by getFluxInstall.
type GetFluxInstallResultOutput struct{ *pulumi.OutputState }

func (GetFluxInstallResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFluxInstallResult)(nil)).Elem()
}

func (o GetFluxInstallResultOutput) ToGetFluxInstallResultOutput() GetFluxInstallResultOutput {
	return o
}

func (o GetFluxInstallResultOutput) ToGetFluxInstallResultOutputWithContext(ctx context.Context) GetFluxInstallResultOutput {
	return o
}

func (o GetFluxInstallResultOutput) Baseurl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *string { return v.Baseurl }).(pulumi.StringPtrOutput)
}

func (o GetFluxInstallResultOutput) ClusterDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *string { return v.ClusterDomain }).(pulumi.StringPtrOutput)
}

func (o GetFluxInstallResultOutput) Components() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetFluxInstallResult) []string { return v.Components }).(pulumi.StringArrayOutput)
}

func (o GetFluxInstallResultOutput) ComponentsExtras() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetFluxInstallResult) []string { return v.ComponentsExtras }).(pulumi.StringArrayOutput)
}

func (o GetFluxInstallResultOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v GetFluxInstallResult) string { return v.Content }).(pulumi.StringOutput)
}

func (o GetFluxInstallResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFluxInstallResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetFluxInstallResultOutput) ImagePullSecrets() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *string { return v.ImagePullSecrets }).(pulumi.StringPtrOutput)
}

func (o GetFluxInstallResultOutput) LogLevel() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *string { return v.LogLevel }).(pulumi.StringPtrOutput)
}

func (o GetFluxInstallResultOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

func (o GetFluxInstallResultOutput) NetworkPolicy() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *bool { return v.NetworkPolicy }).(pulumi.BoolPtrOutput)
}

func (o GetFluxInstallResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v GetFluxInstallResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o GetFluxInstallResultOutput) Registry() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *string { return v.Registry }).(pulumi.StringPtrOutput)
}

func (o GetFluxInstallResultOutput) TargetPath() pulumi.StringOutput {
	return o.ApplyT(func(v GetFluxInstallResult) string { return v.TargetPath }).(pulumi.StringOutput)
}

func (o GetFluxInstallResultOutput) TolerationKeys() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetFluxInstallResult) []string { return v.TolerationKeys }).(pulumi.StringArrayOutput)
}

func (o GetFluxInstallResultOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *string { return v.Version }).(pulumi.StringPtrOutput)
}

func (o GetFluxInstallResultOutput) WatchAllNamespaces() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetFluxInstallResult) *bool { return v.WatchAllNamespaces }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFluxInstallResultOutput{})
}
