# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

__all__ = [
    'Git',
    'GitHttp',
    'GitSsh',
    'Kubernetes',
    'KubernetesExec',
]

@pulumi.output_type
class Git(dict):
    def __init__(__self__, *,
                 url: str,
                 author_email: Optional[str] = None,
                 author_name: Optional[str] = None,
                 branch: Optional[str] = None,
                 commit_message_appendix: Optional[str] = None,
                 gpg_key_id: Optional[str] = None,
                 gpg_key_ring: Optional[str] = None,
                 gpg_passphrase: Optional[str] = None,
                 http: Optional['outputs.GitHttp'] = None,
                 ssh: Optional['outputs.GitSsh'] = None):
        pulumi.set(__self__, "url", url)
        if author_email is not None:
            pulumi.set(__self__, "author_email", author_email)
        if author_name is not None:
            pulumi.set(__self__, "author_name", author_name)
        if branch is not None:
            pulumi.set(__self__, "branch", branch)
        if commit_message_appendix is not None:
            pulumi.set(__self__, "commit_message_appendix", commit_message_appendix)
        if gpg_key_id is not None:
            pulumi.set(__self__, "gpg_key_id", gpg_key_id)
        if gpg_key_ring is not None:
            pulumi.set(__self__, "gpg_key_ring", gpg_key_ring)
        if gpg_passphrase is not None:
            pulumi.set(__self__, "gpg_passphrase", gpg_passphrase)
        if http is not None:
            pulumi.set(__self__, "http", http)
        if ssh is not None:
            pulumi.set(__self__, "ssh", ssh)

    @property
    @pulumi.getter
    def url(self) -> str:
        return pulumi.get(self, "url")

    @property
    @pulumi.getter(name="authorEmail")
    def author_email(self) -> Optional[str]:
        return pulumi.get(self, "author_email")

    @property
    @pulumi.getter(name="authorName")
    def author_name(self) -> Optional[str]:
        return pulumi.get(self, "author_name")

    @property
    @pulumi.getter
    def branch(self) -> Optional[str]:
        return pulumi.get(self, "branch")

    @property
    @pulumi.getter(name="commitMessageAppendix")
    def commit_message_appendix(self) -> Optional[str]:
        return pulumi.get(self, "commit_message_appendix")

    @property
    @pulumi.getter(name="gpgKeyId")
    def gpg_key_id(self) -> Optional[str]:
        return pulumi.get(self, "gpg_key_id")

    @property
    @pulumi.getter(name="gpgKeyRing")
    def gpg_key_ring(self) -> Optional[str]:
        return pulumi.get(self, "gpg_key_ring")

    @property
    @pulumi.getter(name="gpgPassphrase")
    def gpg_passphrase(self) -> Optional[str]:
        return pulumi.get(self, "gpg_passphrase")

    @property
    @pulumi.getter
    def http(self) -> Optional['outputs.GitHttp']:
        return pulumi.get(self, "http")

    @property
    @pulumi.getter
    def ssh(self) -> Optional['outputs.GitSsh']:
        return pulumi.get(self, "ssh")


@pulumi.output_type
class GitHttp(dict):
    def __init__(__self__, *,
                 allow_insecure_http: Optional[bool] = None,
                 certificate_authority: Optional[str] = None,
                 password: Optional[str] = None,
                 username: Optional[str] = None):
        if allow_insecure_http is not None:
            pulumi.set(__self__, "allow_insecure_http", allow_insecure_http)
        if certificate_authority is not None:
            pulumi.set(__self__, "certificate_authority", certificate_authority)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @property
    @pulumi.getter(name="allowInsecureHttp")
    def allow_insecure_http(self) -> Optional[bool]:
        return pulumi.get(self, "allow_insecure_http")

    @property
    @pulumi.getter(name="certificateAuthority")
    def certificate_authority(self) -> Optional[str]:
        return pulumi.get(self, "certificate_authority")

    @property
    @pulumi.getter
    def password(self) -> Optional[str]:
        return pulumi.get(self, "password")

    @property
    @pulumi.getter
    def username(self) -> Optional[str]:
        return pulumi.get(self, "username")


@pulumi.output_type
class GitSsh(dict):
    def __init__(__self__, *,
                 password: Optional[str] = None,
                 private_key: Optional[str] = None,
                 username: Optional[str] = None):
        if password is not None:
            pulumi.set(__self__, "password", password)
        if private_key is not None:
            pulumi.set(__self__, "private_key", private_key)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @property
    @pulumi.getter
    def password(self) -> Optional[str]:
        return pulumi.get(self, "password")

    @property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> Optional[str]:
        return pulumi.get(self, "private_key")

    @property
    @pulumi.getter
    def username(self) -> Optional[str]:
        return pulumi.get(self, "username")


@pulumi.output_type
class Kubernetes(dict):
    def __init__(__self__, *,
                 client_certificate: Optional[str] = None,
                 client_key: Optional[str] = None,
                 cluster_ca_certificate: Optional[str] = None,
                 config_context: Optional[str] = None,
                 config_context_auth_info: Optional[str] = None,
                 config_context_cluster: Optional[str] = None,
                 config_path: Optional[str] = None,
                 config_paths: Optional[Sequence[str]] = None,
                 exec_: Optional['outputs.KubernetesExec'] = None,
                 host: Optional[str] = None,
                 insecure: Optional[bool] = None,
                 password: Optional[str] = None,
                 proxy_url: Optional[str] = None,
                 token: Optional[str] = None,
                 username: Optional[str] = None):
        if client_certificate is not None:
            pulumi.set(__self__, "client_certificate", client_certificate)
        if client_key is not None:
            pulumi.set(__self__, "client_key", client_key)
        if cluster_ca_certificate is not None:
            pulumi.set(__self__, "cluster_ca_certificate", cluster_ca_certificate)
        if config_context is not None:
            pulumi.set(__self__, "config_context", config_context)
        if config_context_auth_info is not None:
            pulumi.set(__self__, "config_context_auth_info", config_context_auth_info)
        if config_context_cluster is not None:
            pulumi.set(__self__, "config_context_cluster", config_context_cluster)
        if config_path is not None:
            pulumi.set(__self__, "config_path", config_path)
        if config_paths is not None:
            pulumi.set(__self__, "config_paths", config_paths)
        if exec_ is not None:
            pulumi.set(__self__, "exec_", exec_)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if insecure is not None:
            pulumi.set(__self__, "insecure", insecure)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if proxy_url is not None:
            pulumi.set(__self__, "proxy_url", proxy_url)
        if token is not None:
            pulumi.set(__self__, "token", token)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @property
    @pulumi.getter(name="clientCertificate")
    def client_certificate(self) -> Optional[str]:
        return pulumi.get(self, "client_certificate")

    @property
    @pulumi.getter(name="clientKey")
    def client_key(self) -> Optional[str]:
        return pulumi.get(self, "client_key")

    @property
    @pulumi.getter(name="clusterCaCertificate")
    def cluster_ca_certificate(self) -> Optional[str]:
        return pulumi.get(self, "cluster_ca_certificate")

    @property
    @pulumi.getter(name="configContext")
    def config_context(self) -> Optional[str]:
        return pulumi.get(self, "config_context")

    @property
    @pulumi.getter(name="configContextAuthInfo")
    def config_context_auth_info(self) -> Optional[str]:
        return pulumi.get(self, "config_context_auth_info")

    @property
    @pulumi.getter(name="configContextCluster")
    def config_context_cluster(self) -> Optional[str]:
        return pulumi.get(self, "config_context_cluster")

    @property
    @pulumi.getter(name="configPath")
    def config_path(self) -> Optional[str]:
        return pulumi.get(self, "config_path")

    @property
    @pulumi.getter(name="configPaths")
    def config_paths(self) -> Optional[Sequence[str]]:
        return pulumi.get(self, "config_paths")

    @property
    @pulumi.getter(name="exec")
    def exec_(self) -> Optional['outputs.KubernetesExec']:
        return pulumi.get(self, "exec_")

    @property
    @pulumi.getter
    def host(self) -> Optional[str]:
        return pulumi.get(self, "host")

    @property
    @pulumi.getter
    def insecure(self) -> Optional[bool]:
        return pulumi.get(self, "insecure")

    @property
    @pulumi.getter
    def password(self) -> Optional[str]:
        return pulumi.get(self, "password")

    @property
    @pulumi.getter(name="proxyUrl")
    def proxy_url(self) -> Optional[str]:
        return pulumi.get(self, "proxy_url")

    @property
    @pulumi.getter
    def token(self) -> Optional[str]:
        return pulumi.get(self, "token")

    @property
    @pulumi.getter
    def username(self) -> Optional[str]:
        return pulumi.get(self, "username")


@pulumi.output_type
class KubernetesExec(dict):
    def __init__(__self__, *,
                 api_version: str,
                 command: str,
                 args: Optional[Sequence[str]] = None,
                 env: Optional[Mapping[str, str]] = None):
        pulumi.set(__self__, "api_version", api_version)
        pulumi.set(__self__, "command", command)
        if args is not None:
            pulumi.set(__self__, "args", args)
        if env is not None:
            pulumi.set(__self__, "env", env)

    @property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> str:
        return pulumi.get(self, "api_version")

    @property
    @pulumi.getter
    def command(self) -> str:
        return pulumi.get(self, "command")

    @property
    @pulumi.getter
    def args(self) -> Optional[Sequence[str]]:
        return pulumi.get(self, "args")

    @property
    @pulumi.getter
    def env(self) -> Optional[Mapping[str, str]]:
        return pulumi.get(self, "env")


