// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Configuration block with settings for Kubernetes.
func GetGit(ctx *pulumi.Context) string {
	return config.Get(ctx, "flux:git")
}

// Configuration block with settings for Kubernetes.
func GetKubernetes(ctx *pulumi.Context) string {
	return config.Get(ctx, "flux:kubernetes")
}
