// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("flux");

/**
 * Configuration block with settings for Kubernetes.
 */
export declare const git: outputs.config.Git | undefined;
Object.defineProperty(exports, "git", {
    get() {
        return __config.getObject<outputs.config.Git>("git");
    },
    enumerable: true,
});

/**
 * Configuration block with settings for Kubernetes.
 */
export declare const kubernetes: outputs.config.Kubernetes | undefined;
Object.defineProperty(exports, "kubernetes", {
    get() {
        return __config.getObject<outputs.config.Kubernetes>("kubernetes");
    },
    enumerable: true,
});

