// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace config {
    export interface Git {
        authorEmail?: string;
        authorName?: string;
        branch?: string;
        commitMessageAppendix?: string;
        gpgKeyId?: string;
        gpgKeyRing?: string;
        gpgPassphrase?: string;
        http?: outputs.config.GitHttp;
        ssh?: outputs.config.GitSsh;
        url: string;
    }

    export interface GitHttp {
        allowInsecureHttp?: boolean;
        certificateAuthority?: string;
        password?: string;
        username?: string;
    }

    export interface GitSsh {
        password?: string;
        privateKey?: string;
        username?: string;
    }

    export interface Kubernetes {
        clientCertificate?: string;
        clientKey?: string;
        clusterCaCertificate?: string;
        configContext?: string;
        configContextAuthInfo?: string;
        configContextCluster?: string;
        configPath?: string;
        configPaths?: string[];
        host?: string;
        insecure?: boolean;
        password?: string;
        proxyUrl?: string;
        token?: string;
        username?: string;
    }

}
