// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flux.Inputs
{

    public sealed class ProviderKubernetesArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientCertificate")]
        public Input<string>? ClientCertificate { get; set; }

        [Input("clientKey")]
        public Input<string>? ClientKey { get; set; }

        [Input("clusterCaCertificate")]
        public Input<string>? ClusterCaCertificate { get; set; }

        [Input("configContext")]
        public Input<string>? ConfigContext { get; set; }

        [Input("configContextAuthInfo")]
        public Input<string>? ConfigContextAuthInfo { get; set; }

        [Input("configContextCluster")]
        public Input<string>? ConfigContextCluster { get; set; }

        [Input("configPath")]
        public Input<string>? ConfigPath { get; set; }

        [Input("configPaths")]
        private InputList<string>? _configPaths;
        public InputList<string> ConfigPaths
        {
            get => _configPaths ?? (_configPaths = new InputList<string>());
            set => _configPaths = value;
        }

        [Input("host")]
        public Input<string>? Host { get; set; }

        [Input("insecure")]
        public Input<bool>? Insecure { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("proxyUrl")]
        public Input<string>? ProxyUrl { get; set; }

        [Input("token")]
        public Input<string>? Token { get; set; }

        [Input("username")]
        public Input<string>? Username { get; set; }

        public ProviderKubernetesArgs()
        {
        }
        public static new ProviderKubernetesArgs Empty => new ProviderKubernetesArgs();
    }
}
