// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getFluxSync(args: GetFluxSyncArgs, opts?: pulumi.InvokeOptions): Promise<GetFluxSyncResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("flux:index/getFluxSync:getFluxSync", {
        "branch": args.branch,
        "commit": args.commit,
        "interval": args.interval,
        "name": args.name,
        "namespace": args.namespace,
        "patchNames": args.patchNames,
        "secret": args.secret,
        "semver": args.semver,
        "tag": args.tag,
        "targetPath": args.targetPath,
        "url": args.url,
    }, opts);
}

/**
 * A collection of arguments for invoking getFluxSync.
 */
export interface GetFluxSyncArgs {
    branch?: string;
    commit?: string;
    interval?: number;
    name?: string;
    namespace?: string;
    patchNames?: string[];
    secret?: string;
    semver?: string;
    tag?: string;
    targetPath: string;
    url: string;
}

/**
 * A collection of values returned by getFluxSync.
 */
export interface GetFluxSyncResult {
    readonly branch?: string;
    readonly commit?: string;
    readonly content: string;
    readonly id: string;
    readonly interval?: number;
    readonly kustomizeContent: string;
    readonly kustomizePath: string;
    readonly name?: string;
    readonly namespace?: string;
    readonly patchFilePaths: {[key: string]: string};
    readonly patchNames?: string[];
    readonly path: string;
    readonly secret?: string;
    readonly semver?: string;
    readonly tag?: string;
    readonly targetPath: string;
    readonly url: string;
}
export function getFluxSyncOutput(args: GetFluxSyncOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFluxSyncResult> {
    return pulumi.output(args).apply((a: any) => getFluxSync(a, opts))
}

/**
 * A collection of arguments for invoking getFluxSync.
 */
export interface GetFluxSyncOutputArgs {
    branch?: pulumi.Input<string>;
    commit?: pulumi.Input<string>;
    interval?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    patchNames?: pulumi.Input<pulumi.Input<string>[]>;
    secret?: pulumi.Input<string>;
    semver?: pulumi.Input<string>;
    tag?: pulumi.Input<string>;
    targetPath: pulumi.Input<string>;
    url: pulumi.Input<string>;
}
